<div class="row">
	<div class="span6">
		<h2>Itenerary</h2>
		<h3>What's going on?</h3>
		<p><em>Please note that all these times are just guidelines that your centre may choose to ignore. They're also likely to change without notice.</em></p>
		<h4>Monday</h4>
		<p>On Monday, everyone will arrive and introductions will be made. Once that's over you'll be planning for your big project.
		Coming up with the idea is always the hardest part: don't underestimate it!</p>
		<p>09.30 &mdash; Arriving in the morning</p>
		<p>10.00 &mdash; Coding continues</p>
		<p>13.00 &mdash; Lunch (obviously)</p>
		<p>17.00 &mdash; Let the ideas brew. See you tomorrow!</p>
		<h4>Tuesday - Thursday</h4>
		<p>On Tuesday, Wednesday and Thursday, the days will follow a fairly similar format. You'll be planning, learning, coding, designing and possibly
		even wiring away with help from your mentors, alumni and hosts. You may even be joining talks by industry experts from across the country.</p>
		<p>09.30 &mdash; Arriving in the morning</p>
		<p>10.00 &mdash; Coding continues</p>
		<p>13.00 &mdash; Lunch (obviously)</p>
		<p>17.00 &mdash; Remember to sleep! See you tomorrow.</p>
		<h4>Friday</h4>
		<p>Friday morning will be mostly the same as the other days; everyone will meet and get coding as usual. However, at around lunch time
		(this, again, depends on your centre), you'll all be rushing off to the Venue (TBA) for the big night of coding. You may do this with
		your family or with other people in your centre. This is one hue sleepover/camping exercise (approximately 500 participants alone!), hopefully marking
		the finish of your projects.</p>
		<p>09.30 &mdash; Arriving in the morning</p>
		<p>10.00 &mdash; Coding continues</p>
		<p>12.30 &mdash; Lunch time</p>
		<p>13.00 &mdash; Leaving for The Venue (TBA) </p>
		<h4>Saturday</h4>
		<p>On Saturday, you'll wake up in time for the scary bit: the presentations. You'll be presenting to industry experts, other
		participants, parents and other curious people to compete for a place in the afternoon final presentations (the bit with the prizes).</p>
		<p>11.00 &mdash; First presentations begin.</p>
		<p>13.30 &mdash; Lunch is served! </p>
		<p>15.00 &mdash; The big presentation; judges, prizes and other awards.</p>
		<p><em>You may also stay on Saturday night if it helps with transport arrangements.</em></p>
	</div>
	<div class="span6 kids-checklists">
		<h2>Checklists</h2>
		<h3>For the Week</h3>
		<p>You'll need to bring with you:</p>
		<ul>
			<li>A laptop &mdash; this can have any operating system or software you like, provided you're comfortable using it. Most of the mentors
			will be using a Mac or Windows PC, so don't bring a Linux (or other) computer if you're not comfortable with coding in it.</li>
			<li>A packed lunch or such &mdash; this is useful for sustinance. Your centre will get in touch with plans in case they've already made arrangements.</li>
			<li>Some programming knowledge &mdash; any amount is useful; the more the better, but don't worry: there'll be people around to help you learn if you're new to it!</li>
			<li>Transport to and from the centre &mdash; again, pretty useful. If there are any problems getting to your local centre, get in touch and we may be able to help. (No promises!)</li>
		</ul>
		<h3>For the Festival of Code</h3>
		<p>You'll need to bring with you:</p>
		<ul>
			<li>A sleeping bag &mdash; more useful stuff</li>
			<li>Funds or some means to get to the site (coordinated by your family or centre)</li>
			<li>You'll still need the laptop from the previous week</li>
			<li>Toiletries and other things you'll need to keep you going for the night and next day</li>
			<li>Your full parents/guardian's contact details (while we're here, make sure they've seen <a href="/parents">the parents section</a>)</li>
			<li>Possibly (dependant on age) your parent or a guardian to come with you. See the parent's section of the website.</li>
		</ul>
	</div>
</div>