<div class="row">
	<div class="span8">
		<h2>How will the week work?</h2>
<p>The idea is that the young developers come in on the Monday morning and have a brainstorming session with your developers and our mentors/alumni who will be with you.</p>
<p>They look at the data on <a href="http://data.gov.uk" target="_blank">data.gov.uk</a> (or other open data we send/detail to you) and choose either a data set they want to play with, or a theme/issue they want to tackle using a variety of open data sets. (We like them to use data from at least one <a href="http://data.gov.uk" target="_blank">data.gov.uk</a> set, it can be mashed with as many other open data sets (or your own) as they like).</p>
<p>They begin to build an idea and can work on this in a group or individually. By the second day, they need to start coding. They will then spend the rest of the week developing their idea and creating it. This will be very lively and communication between centres and mentors over twitter and email is key here — we will keep on top of this.</p>
<p>On the Friday every centre needs to gather their young coders up and bring them all to the festival of code. They will continue coding, hear lightning talks from interesting people and sleep across the site readying themselves for a big show and tell on the Saturday to a mixture of Government, Press and Industry. There will be music. We will co-ordinate this migration with you and yes, it will include getting them home too — but we will help you, don't worry.</p>
<p><em>For a rough guide to how the week may work, a guide itinerary can be found on the <a href="/kids/itinerary.html">kids page</a>.</em></p>.

	</div>
	<div class="span4">
		<h2>Money</h2>
		<p>This event is free for young people to attend, but we are raising sponsorship money for necessities for the festival and a hardship fund for travel through PeopleFund.it as well as private donors, but this is not exactly easy this year! The next way to contribute financially to YRS will be coming soon!</p>
		<p>Ideally we would ask that you provide lunch for your young people, and if you can raise the money to cover that locally, awesome. We will co-ordinate travel arrangements for the Friday with you, this will include details of the young people who need to dip into the hardship fund.</p>
		
	</div>
</div>
