<h2>The Judges</h2>
<div class="row judges">
	<div class="span4">
    <div class="cont">
    <img src="/static/lilycole.jpg" width="225" height="225" alt="Lily Cole">
    <h3>Lily Cole</h3>
    <p><small>Photo by James Moriarty/The North Circular</small></p>
    <p>The actress and ethical campaigner was was originally introduced to Rewired State to help develop her social giving site impossible.com. The new tech entrepreneur said about being asked to judge for Young Rewired State; "I am really looking forward to Young Rewired State. I can't wait to see what these kids create and discover genius coders."</p>
    <p><a href="http://en.wikipedia.org/wiki/Lily_Cole">Lily Cole on Wikipedia</a><br>
      <a href="http://www.youtube.com/watch?v=cSGn097HZ00">Beyond Ourselves - Becky Anderson, Lily Cole & Jimmy Wales - Zeitgeist 2012</a></p>
    </div></div>
	<div class="span4">
    <div class="cont">
    <img src="/static/Conrad_067.jpg" width="225" height="225" alt="Conrad Wolfram">
    <h3>Conrad Wolfram</h3>
    <p>Mathematician, programmer, technologist and founder of Wolfram Research said; "Coding is the technical language of creativity, so it's great to be helping to judge our brightest young coders' work. And what better year than Turing's centenary?"</p>
    <p><a href="http://www.conradwolfram.com/">http://conradwolfram.com</a></p>
    </div></div>
	<div class="span4">
    <div class="cont">
    <img src="/static/aral-headshot-high-res.jpg" width="225" height="225" alt="Aral Balkin">
    <h3>Aral Balkin</h3>
    <p>Experienced designer and developer said; "Programming taught me that I can make things, that I can change the world around me, and that my imagination truly is the only limit. That's why events like Festival of Code are so important. Programming is the new literacy and initiatives like the Festival of Code are essential catalysts in inspiring and empowering the Shakespeares of tomorrow".</p>
    <p><a href="http://aralbalkan.com/">http://aralbalkin.com</a></p>
    </div></div>
	<div class="span4">
    <div class="cont">
    <img src="/static/JonathanLuff.jpg" width="225" height="225" alt="Jonathan Luff">
    <h3>Jonathan Luff</h3>
    <p>Advisor at No 10 and Director of the GREAT campaign "I am really pleased to be a Young Rewired State judge again. If the last time is anything to go by, my fellow judges and I will be blown away by the talent and creativity of the kids involved. I can't wait to see what they can produce."</p>
    <p><a href="http://uk.linkedin.com/pub/jonathan-luff/39/993/b77">Jonathan Luff on LinkedIn</a>
    </p>
    </div></div>
	<div class="span4">
    <div class="cont">
    <img src="/static/thomasgrassl.jpg" width="225" height="225" alt="Thomas Grassl">
    <h3>Thomas Grassl</h3>
    <p>Thomas Grassl is Senior Director leading SAP's Global Developer Relations programs for Mobile, Databases, Cloud, Tools and APIs. "Developers bring ideas, software and innovation to life. We at SAP are very excited to be a part of this event and support young developers in their journey to become the next generation that will shape the future and help the world run better. I'm looking forward to many exciting and inspiring ideas and to congratulating the winners."</p>
    </div></div>
</div>

<h2>The Compere</h2>
<div class="row judges">
	<div class="span4">
    <div class="cont">
    <img src="/static/dallas_small.jpg" width="225" height="225" alt="Dallas Campbell">
    <h3>Dallas Campbell</h3>
    <p>Actor, presenter and writer said: “ I am thrilled to be involved in YRS this year, it is a great honour and I look forward to seeing the fantastic ideas the kids come up with”</p>
    </div></div>
</div>

<div class="row"><div class="span12">
<h2>About the Festival</h2>
<div class="row"><div class="span8">
<p>Friday 10th to Sunday 12th sees the grand final of the SAP Young Rewired State 2012 week. On the Friday night the young programmers will all come to the Custard Factory in Birmingham and have fireside chats whilst they code with wonderful people who are programmers doing great things, including representatives from Raspberry Pi, London Zoo and Twilio amongst many others. Whilst they finish coding their apps and preparing their presentations they will be able to hear, chat and interact with some of the UK's greatest digital visionaries.</p>

<p>They will have a massive sleepover in the Custard Factory preparing for the Saturday show and tell. Saturday brings a morning of heats where each centre will present in five concurrent streams, to five panels of esteemed judges with winners in four prize categories (Best in Show - sponsored by SAP, Best example of Coding, Wish I had thought of that and Code a better Country) going forward to the Grand Finale in the afternoon.</p>

<p>The afternoon finale will be compered by Dallas Campbell from Bang Goes the Theory, who is also a morning judge - a busy lad.</p>

<p>Prizes are awarded in the evening and then everyone can relax and celebrate underneath the arches of the Custard Factory.</p>

<p>The schedule for the Festival of Code in full is here: <a href="http://lanyrd.com/2012/festival-of-code/">Festival of Code on Lanyrd</a></p>

<p style="font-weight:bold;color:#920">Be warned, we are proudly not funded by government, your tax money is better spent elsewhere, we rely only on sponsorship and run this event at no profit, every penny goes into making this happen (not people fees) - which is quite expensive even though we get away with a lot of donated stuff... and people. However, we cannot stretch to supplying you with food and booze, even though we would love to, so please bring cash with you for the bar and food concessions we will have on site.</p>
</div>
<div class="span4">
<div class="well well-large">
<h3>Tickets still available!</h3>
<p>Be stunned by the outcome of the week. Get tickets for the Festival of Code now.</p>
<a href="http://yrs12foc.eventbrite.com/" class="btn btn-primary">Get tickets now! &rarr;</a></div>
</div>
</div>
<h2 style="margin-top:50px;">Delivery Partners</h2>
<p>A big Thank You to the businesses and organisations that have helped us be able to put on this year's Festival of Code.</p>

  <ul class="deliv-partners">
    <li>
      <p><a href="http://uk.linkedin.com/in/lararatnaraja"><img alt="Lara Ratnaraja" src="http://youngrewiredstate.org/img/sponsors/lara-1.jpg"></a></p>
    </li>
    
    <li>
      <p><a href="http://www.custardfactory.co.uk/"><img alt="Custard Factory" src="http://youngrewiredstate.org/img/sponsors/CustardFactory.jpg"></a></p>
    </li>
    
    <li>
      <p><a href="http://bigcatgroup.co.uk/"><img alt="Big Cat Group" src="http://youngrewiredstate.org/img/sponsors/BigCat.jpg"></a></p>
    </li>
    <li>
      <p><a href="http://youngrewiredstate.org/festival/www.bcu.ac.uk/business"><img alt="Birmingham City University" src="http://youngrewiredstate.org/img/sponsors/BCULogo.jpg"></a></p>
    </li>
    
    <li>
      <p><a href="http://www.birmingham.ac.uk/index.aspx"><img alt="University of Birmingham" src="http://youngrewiredstate.org/img/sponsors/BhamUni.jpg"></a></p>
    </li>
    
    <li>
      <p><a href="http://www.microteam.co.uk/"><img alt="Microteam Limited" src="http://youngrewiredstate.org/img/sponsors/MTlogo.jpg"></a></p>
    </li>
    <li>
      <p><a href="http://www.digitalbirmingham.co.uk/"><img alt="Digital Birmingham" src="http://youngrewiredstate.org/img/sponsors/digibrum.jpg"></a></p>
    </li>
    
    <li>
      <p><a href="http://www.birmingham.gov.uk/"><img alt="Birmingham City Council" src="http://youngrewiredstate.org/img/sponsors/bcclogo.png"></a></p>
    </li>
    
    <li>
      <p><a href="http://www.electricstage.co.uk/"><img alt="Electric Stage Co" src="http://youngrewiredstate.org/img/sponsors/esclogo.jpg"></a></p>
    </li>
    <li>
      <p><a href="http://www.yummcafe.co.uk/"><img alt="Yumm Cafe" src="http://youngrewiredstate.org/img/sponsors/yummcafe_logo.jpg"></a></p>
    </li>
    
    <li>
      <p><a href="http://bayleaf-restaurant.co.uk/"><img alt="Bay Leaf" src="http://youngrewiredstate.org/img/sponsors/bayleafcafe.png"></a></p>
    </li>
    <li>
      <p><a href="http://keyoneproductions.co.uk"><img alt="Keyone Productions" src="http://youngrewiredstate.org/img/sponsors/Keyone_Productions_Final.png"></a></p>
    </li>
  </ul>
</div>
<br>
<p>&nbsp;</p>
</div></div>	
