<div class="row">
	<div class="span8">
		<h2>Videos</h2>
		<p>Here are some videos from before and during the event: </p>

		<ul>
			<li><a href="http://youtu.be/erTUl9m4-to">Emma and Lawrence introduce SAP YRS 2012</a></li>
			<li><a href="http://youtu.be/uirWZz6ZOro">Brandon presents TruMPs for Android</a></li>
			<li><a href="http://youtu.be/3wa9zNazrl8">Creative Computing Club report in from Ipswich</a></li>
			<li><a href="http://youtu.be/Kj-rncj0kpM">Weather Flight by Greg and Justin Auger</a></li>
			
			
		</ul>

	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Signups for SAP YRS 2012 are now closed. Express interest in the even-bigger YRS 2013!</p>
			<p><a href="./signup.html" class="btn btn">Sign up now! &rarr;</a></p>
		</div>
		<img src="http://farm7.staticflickr.com/6009/6012388041_39aa2c3686_b.jpg" />
	</div>
</div>