<div class="row">
	<div class="span8">
	
		<h2>The Hacks</h2>
		
		<p><a href="http://hacks.rewiredstate.org/events/yrs2012">All the hacks in one place!</a></p>
	
		<h2>Videos</h2>
		<p>Here are some videos from before and during the event: </p>

		<ul>
			<li><a href="http://youtu.be/erTUl9m4-to">Emma and Lawrence introduce SAP YRS 2012</a></li>
			<li><a href="http://youtu.be/uirWZz6ZOro">Brandon presents TruMPs for Android</a></li>
			<li><a href="http://youtu.be/3wa9zNazrl8">Creative Computing Club report in from Ipswich</a></li>
			<li><a href="http://youtu.be/Kj-rncj0kpM">Weather Fight by Greg and Justin Auger</a></li>
			<li><a href="http://youtu.be/nG4STg0HuAE">RadioSight from ionCube centre</a></li>
			<li><a href="http://youtu.be/_kKi7sTwZFg">Medal Run by Kieran, Aidan (with a bit of help from Mo)</a></li>
			<li><a href="http://new.livestream.com/keyone/yrs2012">Winners announcements and prize presentations	</a></li>
			<li><a href="http://youtu.be/uHJz13dRKms">YRS 2012 Thank You video</a></li>
			<li><a href="http://youtu.be/DdaiRiKn3kA">Feedback from one our SAP judges</a></li>			
		</ul>
		
		<h2>Photos</h2>
		
		<p><a href="http://www.flickr.com/search/?q=yrs2012&ss=2&s=int">Search for yrs2012 on Flickr</a></p>
		
		
	
		

	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Signups for SAP YRS 2012 are now closed. Express interest in the even-bigger YRS 2013!</p>
			<p><a href="./signup.html" class="btn btn">Sign up now! &rarr;</a></p>
		</div>
		<img src="http://farm9.staticflickr.com/8308/7759299642_e79b6fbe65_n.jpg" width="320" height="220" alt="YRS2012_079" />
	</div>
</div>