<div class="row">
	<div class="span8">
	
		<h2>The Hacks</h2>
			<p><a href="http://hacks.rewiredstate.org/events/yrs2012">All the hacks in one place!</a></p>
	
	
		<h2>Videos</h2>
			<p>Here are some videos from before, during and after the event: </p>

		<ul>
			<strong>Before</strong>
			<li><a href="http://youtu.be/erTUl9m4-to">Emma and Lawrence introduce SAP YRS 2012</a></li>
			<li><a href="http://www.youtube.com/watch?v=25WuyA8qLwI">A message of support from DJ Adams of SAP</a></li>
			<strong>During</strong>
			<li><a href="https://vimeo.com/madlabuk">MadLab from Manchester's Vimeo channel</a></li>
			<li><a href="http://youtu.be/uirWZz6ZOro">Brandon presents TruMPs for Android</a></li>
			<li><a href="http://youtu.be/3wa9zNazrl8">Creative Computing Club report in from Ipswich</a></li>
			<li><a href="http://youtu.be/Kj-rncj0kpM">Weather Fight by Greg and Justin Auger</a></li>
			<li><a href="http://youtu.be/nG4STg0HuAE">RadioSight from ionCube centre</a></li>
			<li><a href="http://youtu.be/_kKi7sTwZFg">Medal Run by Kieran, Aidan (with a bit of help from Mo)</a></li>
			<li><a href="http://new.livestream.com/keyone/yrs2012">Winners announcements and prize presentations	</a></li>
			<strong>After</strong>
			<li><a href="http://youtu.be/uHJz13dRKms">YRS 2012 Thank You video</a></li>
			<li><a href="http://youtu.be/DdaiRiKn3kA">Feedback from one our SAP judges</a></li>
			<li><a href="http://youtu.be/YLKhGWxjh-w">SAP YRS 2012 - A Snapshot</a></li>
			<li><a href="http://youtu.be/aIfjATM3DgU">SAP YRS 2012 - A Little More Depth</a></li>
					
		</ul>
		
		
		<h2>Photos</h2>
		
			<ul>
				<li><a href="http://www.flickr.com/search/?q=yrs2012&ss=2&s=int">Search for yrs2012 on Flickr</a></li>
				<li><a href="http://www.flickr.com/photos/paul_clarke/sets/72157631014746400/">YRS 2012 by Paul Clarke (Flickr)</a></li>
				<li><a href="http://www.flickr.com/photos/smudgypixels/sets/72157631093615960/">YRS 2012 by Jessie and Lottie</a></li>
				<li><a href="http://www.flickr.com/photos/gt_p/sets/72157631094924452/">SAP YRS2012 at The Custard Factory by Gordon Tant (Flickr)</a></li>
				<li><a href="https://www.facebook.com/media/set/?set=a.146518502154321.31145.110152649124240&type=3">import.io Facebook gallery</a></li>
				<li><a href="http://www.flickr.com/photos/simionp/sets/72157631038385278/">YRS 2012 Part One by Simion Putina (Flickr)</a></li>
				<li><a href="http://www.flickr.com/photos/simionp/sets/72157631053144096/">YRS 2012 Part Two by Simion Putina (Flickr)</a></li>
				<li><a href="http://www.flickr.com/photos/madlabuk/collections/72157631003725392/">YRS 2012 at MadLab (Flickr)</a></li>
				<li><a href="https://www.facebook.com/media/set/?set=a.10151093573558967.460698.307023978966&type=3">Young Rewired State 2012 by SenGrid (Facebook)</a></li>
				
			</ul>
	
		
		<h2>Press and Blogs</h2>
		
			<ul>
				<li><a href="http://www.kernelmag.com/scene/3093/yrs-2012/">Fuelling the Start-Ups of Tomorrow (The Kernel)</a></li>
				<li><a href="http://www.kernelmag.com/scene/3019/young-rewired-state-2012-kicks-off/">Young Rewired State 2012 Kicks Off (The Kernel)</a></li>
				<li><a href="http://www.wired.co.uk/news/archive/2012-08/10/digital-olympics">A young programer's account of Rewired State's Festival of Code (Wired UK)</a></li>
				<li><a href="http://www.digitalbirmingham.co.uk/blog/yrs-is-jaw-dropping-success">YRS is jaw dropping success (Digital Birmingham)</a></li>
				<li><a href="http://indigotrust.wordpress.com/2012/08/17/young-gifted-and-coding/">Young, Gifted and Coding (Indigo Trust)</a></li>
				<li><a href="https://www.gosquared.com/blog/archives/3250">Young Rewired State 2012 (GoSquared)</a></li>
				<li><a href="http://sendgrid.com/blog/young-rewired-state-coding-a-better-world/">Young Rewired State: Coding a Better WORLD (SendGrid)</a></li>
				<li><a href="http://developer.pearson.com/blog/my-week-young-rewired-state-2012">My Week With the Young Rewired State 2012 (Pearson)</a></li>
				<li><a href="http://drblack.posterous.com/young-rewired-state-and-my-brother-stephen">Young Rewired State and my brother Stephen (Dr Sue Black)</a></li>
				<li><a href="http://jaybyjayfresh.com/2012/08/11/young-rewired-state-finals/">Live blogging of the finale (Jay from Jayfresh)</a></li>
				<li><a href="http://www.sequence.co.uk/en/sitecore/content/Blog/YRS2012.aspx">Young Rewired State 2012 (Sequence)</a></li>
				<li><a href="http://fluxxhasateam.tumblr.com">Fluxx has a team</a></li>
				<li><a href="http://zcint.co.uk/article/judges-amazed-by-young-rewired-state-coders">Judges “Amazed” By Young Rewired State Coders (ZConnection)</a></li>
				<li><a href="http://www.openkent.org.uk/index.php/blog/kcc-hosted-hack-day-for-young-creatives/">KCC hosted hack day for young creatives (Open Kent)</a></li>
				<li><a href="http://www.thisiskent.co.uk/Young-people-needed-programming-festival/story-16521966-detail/story.html">Young people needed for IT programming festival (This is Kent)</a></li>
				<li><a href="http://www.guardian.co.uk/technology/2012/jul/02/lily-cole-judge-young-rewired-competition">Lily Cole to judge Young Rewired programming competition (The Guardian)</a></li>
				<li><a href="http://www.computerweekly.com/news/2240159076/Lily-Cole-to-judge-Young-Rewired-State-Competition">Lily Cole to judge Young Rewired State Competition (Computer Weekly)</a></li>
				<li><a href="http://manchester.girlgeekdinners.com/2012/06/29/1151/">An Introduction to Coding with Young Rewired State (Manchester Girl Geeks)</a></li>
				<li><a href="http://www.thisisbath.co.uk/Bath-teenagers-programmed-Young-Rewired-State/story-16682175-detail/story.html">Bath teenagers programmed for Young Rewired State Festival of Code (This is Bath)</a></li>
				<li><a href="http://www.librarydust.info/?p=317">Young Rewired State (Library Dust)</a></li>
				<li><a href="http://craigsnowden.com/index.php/posts/yrs-2012">Young Rewired State 2012 (Craig Snowden)</a></li>
				<li><a href="http://www.cogapp.com/blog/young-rewired-state-2012">Young Rewired State 2012 (Cogapp)>/a></li>
				<li><a href="http://whatyoula.blogspot.co.uk/2012/08/young-rewired-state-2012-from-outsider.html">Young Rewired State 2012 - From an outsider (Lynn Heckles)</a></li>
				<li><a href="http://codeboom.wordpress.com/2012/08/15/yrs-epq-and-the-return-of-the-king-of-code/">YRS, EPQ and the Return of the King (of Code) (Code;Boom)</a></li>
				<li><a href="http://www.citysdk.eu/2012/08/15/young-rewired-state-thrives-on-open-data/">Young Rewired State Thrives On Open Data (Cuty SDK)</a></li>
				<li><a href="http://raspberrypi4t.wordpress.com/category/young-rewired-state/">YRS – The Big Day Is Here!!!! AHHHHHH (Kid Coder)</a></li>
				<li><a href="http://www.ubelly.com/2012/08/sap-young-rewired-state-2012/">SAP Young Rewired State 2012 (Ubelly)</a></li>
				<li><a href="http://northliverpoolacademy.com/thestudio/the-studio-at-nla-participates-in-young-rewired-states-festival-of-code-2012/">The Studio at NLA participates in Young Rewired States “Festival of Code 2012”</a></li>
				
			</ul>
		
		<h2>Audio</h2>
			<ul>
				<li><a href="http://download.guardian.co.uk/audio/kip/technology/series/techweekly/1344347653104/8784/gnl.tech.120807.jp.tech_weekly.mp3">Tech Weekly podcast: Lily Cole on why kids must code (mp3 file)</a></li>
				<li><a href="http://www.disruptivesocialcare.com/wp-content/uploads/DSCP_05_17Aug12.mp3">Disruptive Social Care Podcast 5</a></li>
				
			</ul>		
	
		

	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Signups for SAP YRS 2012 are now closed. Express interest in the even-bigger YRS 2013!</p>
			<p><a href="./signup.html" class="btn btn">Sign up now! &rarr;</a></p>
		</div>
		<img src="http://farm9.staticflickr.com/8308/7759299642_e79b6fbe65_n.jpg" width="320" height="220" alt="YRS2012_079" />
	</div>
</div>
