<p>Moving 1,000 people around the country can be a pain, so we have a kick-ass team of YRS'ers to help.
The best way to get a quick response is via our Twitter, phones or by email, so they're below. If you're a young person, the best email address to use is kids@, and if you're a parent wanting to know more, the best person to ask is angie@.</p>
<style>.festivaltickets {display:none}</style>

<table class="table table-bordered">
    <thead>
        <tr>
            <th colspan="2">Query</th>
            <th>Person</th>
            <th >Email</th>
            <th >Phone</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="7"><strong>General</strong></td>
            <td>General Questions</td>
            <td>YRS Team</td>
            <td><a href="mailto:hello@youngrewiredstate.org">hello@</a></td>
            <td>-</td>
        </tr>
        <tr>
          <td>Operations</td>
          <td>Emma M</td>
          <td><a href="mailto:emma@rewiredstate.org">emma@</a></td>
          <td>07730 570647</td>
        </tr>
        <tr>
            <td rowspan="2">General Questions</td>
            <td>Debbie</td>
            <td><a href="mailto:hello@youngrewiredstate.org">hello@</a></td>
            <td>07446 868816</td>
        </tr>
        <tr>
            <td>Charles</td>
            <td><a href="mailto:hello@youngrewiredstate.org">hello@</a></td>
            <td>07446 916179</td>
        </tr>
        <tr>
          <td>Volunteers</td>
            <td>YRS Team</td>
            <td><a href="mailto:volunteers@youngrewiredstate.org">volunteers@</a></td>
            <td>-</td>
        </tr>
        <tr>
          <td>Press</td>
          <td>Stephanie L</td>
          <td><a href="mailto:press@youngrewiredstate.org">press@</a></td>
          <td>07730 570647</td>
        </tr>
        <tr>
          <td>Sponsors</td>
          <td>Emma M</td>
          <td><a href="mailto:emma@rewiredstate.org">emma@</a></td>
          <td>07730 570647</td>
        </tr>
        <tr>
          <td><strong>Young people</strong> - send any questions here</td>
          <td>General</td>
          <td>Emma &amp; Neil</td>
          <td><a href="mailto:kids@youngrewiredstate.org">kids@</a></td>
          <td>-</td>
        </tr><tr>
          <td colspan="2"><strong>Parents</strong>; if you've any questions</td>
          <td>Angi L</td>
          <td><a href="mailto:angijlong@gmail.com">angi@</a></td>
          <td> </td>
        </tr>
        <tr>
          <td colspan="2"><strong>Centres</strong>; prospectus and current</td>
          <td rowspan="2">Neil F</td>
          <td rowspan="2"><a href="mailto:neil@rewiredstate.org">neil@</a></td>
          <td rowspan="2">07525 246356</td>
        </tr>
        <tr>
          <td colspan="2"><strong>Mentors</strong>; prospectus and current</td>
          <td rowspan="2">Neil F</td>
          <td rowspan="2"><a href="mailto:neil@rewiredstate.org">neil@</a></td>
          <td rowspan="2">07525 246356</td>          
        </tr>
    </tbody>
</table>
