<div class="row">
	<div class="span8">
		<p>In order to have the festival and enjoy our time together without fear we have taken some precautions. We have separated out the sleeping arrangements according to age groups. Under 14s will be in a secured building and will have parents attending with them. CRB checked adults will be in charge of the 14-18 year olds and they will be sleeping in the library. 18 and overs will be sleeping in Area 2 of the Custard Factory a huge space but completely contained.</p>
		<p>Only CRB checked adults will man the central operations area, this includes the 'sick bay'.</p>
		<p>We have an army of volunteers for during the days who will ensure that everyone is accounted for and in the right place at the right time.</p>
	</div>
	<div class="span4">
		<img src="http://farm7.staticflickr.com/6006/6012039943_3fd7b8f0d2_b.jpg" class="fluid" />
	</div>
</div>