        <div class="hero-unit">
        <h1>Festival of Code 2012</h1>
        <p>50 centres across the UK, 6th to 12th August 2012. The largest free event in the UK aimed at young coders, engineers and geeks is celebrating its fourth annual event. Don't miss out: sign up now.</p>
        <p><a class="btn btn-danger btn-large">Get signed up now! &rarr;</a> <a class="btn btn-large">Register a centre &rarr;</a> <a class="btn btn-large">Got skillz? Mentor! &rarr;</a></p>
      </div>
    <div class="row" style="margin-bottom:30px;margin-top:30px; clear:both">
    <div class="span8">
        <ul class="nav nav-tabs" id="yrs-info-tabs">
            <li class="active"><a href="#about-the-event">About The Event</a></li>
            <li><a href="#about-yrs">About Young Rewired State</a></li>
            <li><a href="#last-year">Last Year</a></li>
        </ul>
        
        <div class="tab-content">
        <div class="tab-pane active" id="about-the-event">
                <p style="line-height:150%;color:#333">Young Rewired State (YRS) is a spin-off event from the Rewired State series. Born from a combination of improving young people's access to technology and engineering with Rewired States mission of openness, we present to you: the annual Festival of Code.</p>
                <p style="line-height:150%;color:#333">The week-long event in 2012 runs from the <strong>6th to the 12th August</strong>. During that week businesses, small and large, around the country act as hosts to local young people, YRS alumni, Rewired State mentors and other volunteers. YRSers will be challenged to build digital products: mobile and web, using at least one piece of open data. It is <strong>free for every under 18</strong> to enter. If you are interested, here's what you'll need:</p>
                <ul>
                  <li>A laptop (any laptop you like, as long as you're comfortable using it)</li>
                  <li>At least a very basic understanding of programming, spreadsheets or graphics</li>
                </ul>
                <p style="line-height:150%;color:#333">At the end of the week everyone piles on coaches, trains and cars to the <a href="http://">The Custard Factory in Birmingham</a> where you will have a night of camp and code, pizza and camaraderie.</p>
                <p style="line-height:150%;color:#333">On the Saturday, show off your creations to press, government and industry. Friends are made, lives are changed and, most importantly, prizes are given!</p>
		  </div>
            <div class="tab-pane" id="about-yrs">
                <p style="line-height:150%;color:#666">Young Rewired State is the philanthropic arm of Rewired State. Our primary focus is to find and foster the young children and teenagers who are driven to teaching themselves how to code, how to program the world around them. This is a mighty challenge though well-supported with free tutorials online, but inevitably an isolating and solitary activity.</p>
                <p style="line-height:150%;color:#666">The community of Rewired Staters, YRS alumni and current YRSers enables peer to peer learning and ends the often isolating experience of teaching yourself to code.</p>
			</div>
            <div class="tab-pane" id="last-year">
                <p style="line-height:150%;"><iframe width="100%" height="480" src="http://www.youtube.com/embed/odT4cgd7d8c?rel=0&theme=white" frameborder="0" allowfullscreen></iframe></p>
			</div>
        </div>
        
            
    </div>
    <div class="span4">
            <blockquote style="font-family:Arial, Helvetica, sans-serif;font-size:36px;font-weight:bold;line-height:145%">Challenge yourself to build <span style="color:#B63322">digital products</span> using <span style="color:#B63322">open data</span> to improve the world around you.</blockquote>
    </div>
    <br style="clear:both">
    </div>
    <div class="row">
    	<div class="span4"><div class="well well-large">
        	<h2 id="kids">Young Programmers</h2>
            <p>Heard enough? Sign up to attend the nearest Young Rewired
            State event to you. We already have events in Wales and England
            and there are more to come around the world, so watch this space.<br /><br /><a href="/kids/">More info &raquo;</a></p>
        </div></div>
    	<div class="span4"><div class="well well-large">
            <h2 id="parents">Parents</h2>
            <p>Want to find out a little more about the people behind Young
            Rewired State? Talk with parents of past YRS attendees who have volunteered to help<br /><br /><a href="/parents/">Find out more &raquo;</a></p>
        </div></div>
    	<div class="span4"><div class="well well-large">
            <h2 id="mentors">Mentors</h2>
            <p>Are you a geek over 18? Don't worry, you can sign up
            to become a Young Rewired State mentor and share
            your knowledge with YRS2012 attendees.<br /><br /><a href="/mentors/">Find out more &raquo;</a></p>
        </div></div>
	</div>
    <div class="row">
    	<div class="span4"><div class="well well-large">
            <h2 id="centres">Centres</h2>
            <p>Young Rewired State is a decentralized event that runs
            at multiple centres across the country. If you have some
            spare office space for a week and you're a technical
            organization then contact us!<br /><br /><a href="/centres/">Find out more &raquo;</a></p>
        </div></div>
    	<div class="span4"><div class="well well-large">
            <h2 id="volunteer">Volunteer</h2>
            <p>We need volunteers to help run YRS2012, everything
            from copywriters to event organizers to community
            managers. If you have some spare time, drop us an email
            and tell us how you can help<br /><br /><a href="mailto:volunteers@youngrewiredstate.org">Get in contact &raquo;</a></p>
        </div></div>
    	<div class="span4"><div class="well well-large">
            <h2 id="donate">Donate</h2>
            <p>Young Rewired State is a not-for-profit organization, we don't
            take Intellectual Property and we definitely don't act as a big
            recruiting agency, we rely entirely on sponsorship and donations.
            We used PeopleFund.it to raise 20k. <a href="mailto:hello@youngrewiredstate.org">Corporate sponsorship</a> is being raised privately.</p>
        </div></div>
    </div>
<!-- automagically add content -->
    <div id="section1">

	<p>&nbsp;</p>

</div><!-- closing section1 -->

<div id="section2">
  <div class="container">
	<div class="row">
    <div class="span4">
      <h2 id="learn">Learn from others</h2>
      <p>Learn more about programming by working with other programmers. Quiz mentors and other YRSers about the stuff you want to learn and share your knowledge too.</p>
    </div><!-- closing span4 -->

    <div class="span4">
      <h2 id="teams">Build in teams</h2>
      <p>The opportunity to build something cool with a team of other talented young developers. Work on bringing your ideas to life in code and help other developers bring theirs to life too.</p>
    </div><!-- closing span4 -->

    <div class="span4">
      <h2 id="community">Join the community</h2>
      <p>After the event you're automatically a part of the growing network of young developers across the UK. Lifetime friendships are born as well as businesses. Mentor relationships are forged so you're no longer coding alone.</p>
    </div><!-- closing span4 -->
    </div>
  </div><!-- closing container -->
</div><!-- closing section2 -->
