<h2>Very Important Information</h2>
  <p>You are here because you are talented developers. We hope that being involved in SAP 
    Young Rewired State 2012 gives you opportunities to use that talent and encourages you to 
    pursue and develop that talent in future. This hope is shared by everyone involved with
    Young Rewired State and some are well placed to offer you those opportunities. However, 
    it is really important to us that your talent is not exploited and your youth is not taken 
    advantage of.</p>
  <p>
    For this reason we ask you to be extremely cautious when accepting any form of mentoring, 
    assistance or work beyond the Festival itself. If you are approached by an individual or an 
    organisation we advise you to do the following:</p>
  <ul>
    <li> Speak to an adult who has experience in business and who you trust; perhaps a 
      parent, guardian, teacher or member of YRS staff.</li>
    <li> If you can't think of anyone to talk to contact Thayer Prime (the YRS recruitment 
      guru) at thayer@thayerprime.com.</li>
    <li> Ask the person making you the offer to write down exactly what they are offering 
      you and what they expect from you in return.</li>
    <li> Make sure the agreement you have with them is for a set period of time, we would 
      recommend a trial period of no more than 6 months. This means that if it isn't going 
      well you can leave after that period of time and if it is going well you can always 
      renew the agreement.</li>
    <li> Clarify whether the good ideas you come up with and the cool things you create,
      while they're helping you or you're working for them, belong to you or to them. 
      You don't want to invent the next big thing and then discover the rights to it don't 
      belong to you and someone else is going to get all the credit.</li>
  </ul>
  <p>
    Some great opportunities come out of being involved with YRS so we are certainly not 
    telling you to dismiss every offer that comes your way.  Plenty of individuals and 
    organisations want to help you grow your talents and give you the space and facilities to do 
    so – this is a good thing! We just want you to make sure you understand exactly what it is 
    you'll be agreeing to and that it benefits you as much as it benefits them.</p>
  <p> If you have any more questions about what this advice means then feel free to approach any member 
    of YRS staff and they will help you out.</p>
  </p>