<div class="row">
	<div class="span12">
		<iframe src="https://cms.youngrewiredstate.org/data/api/centres.example" style="width: 100%; height: 620px; border: none;"></iframe>
		
	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Signups for 2012 are now closed. Express interest in the even-bigger YRS 2013!</p>
			<p><a href="./signup.html" class="btn btn-primary">Sign up now! &rarr;</a></p>
		</div>
	</div>
	<div class="span8">
		<h2>SAP YRS Festival of Code 2012</h2>
		<p>The event is spread across the entire of the UK. Even if we can't find a centre near enough to you, we may be able to work something out by mentoring you remotely,
		finding accomodation or providing a hardship fund (in very select cases, deemed so by us). We want everyone to be able to take part. If you can't find a centre close enough, please sign up anyway and we can see what we can do. 
		If you think that you may need help, please let us know as soon as possible.</p>
	</div>
</div>