<style>

ul.resources {
	margin:0px;
	padding:0px;
}

ul.resources li {
	padding:10px;
	border:#999 1px solid;
	margin:0px 20px 20px 0px;
	list-style:none;
	width:190px;
	float:left;
	height:140px;
	overflow:hidden;
}

h3 {clear:both;margin:10px;}

</style>
<iframe width="49%" height="300" src="http://www.youtube.com/embed/erTUl9m4-to?rel=0" frameborder="0" allowfullscreen></iframe>
<iframe width="49%" height="300" src="http://www.youtube.com/embed/25WuyA8qLwI?rel=0" frameborder="0" allowfullscreen></iframe>
<h3>Start with Basics</h3>
<ul class="resources">

    <li>
      <h4><a href="http://www.codecademy.com/">CodeCademy</a></h4>
      <p>An awesome resource to learn to code from the beginning. Starts in Javascript.</p>
    </li>
	
    <li>
      <h4><a href="http://teachyourselftocode.com/">Teach yourself to code</a></h4>
      <p>The web is a fantastic stockpile of resources for people who want to learn programming but it can be hard to know where to start.</p>
    </li>

    <li>
      <h4><a href="https://developer.mozilla.org/en-US/learn">Mozilla Guides to HTML, CSS, and JavaScript</a></h4>
      <p>Community edited, to provide a set of effective and comprehensive guides.</p>
    </li>

    <li>
      <h4><a href="https://developer.mozilla.org/en-US/learn/html">Mozilla Guides to HTML</a></h4>
      <p>Introductory and Advanced guides to learning HTML &#8212; tutorials and training materials.</p>
    </li>

    <li>
      <h4><a href="https://developer.mozilla.org/en-US/learn/css">Mozilla Guides to CSS</a></h4>
      <p>Introductory, Intermediate, and Advanced guides to learning CSS &#8212; tutorials and training materials.</p>
    </li>

    <li>
      <h4><a href="https://developer.mozilla.org/en-US/learn/javascript">Mozilla Guides to JavaScript</a></h4>
      <p>MDN articles about learning/improving JavaScript.</p>
    </li>

    <li>
      <h4><a href="http://learn.shayhowe.com/html-css/terminology-syntax-intro/">Guide to HTML & CSS</a></h4>
      <p>A great guide to HTML &amp; CSS, updated weekly.</p>
    </li>

	<li>
      <h4><a href="http://kidsruby.com/">Kid's Ruby</a></h4>
      <p>Simple, free, and fun.</p>
    </li>
</ul>

<h3>&hellip;then Challenge Yourself</h3>
<ul class="resources">

    <li>
      <h4><a href="http://ruby.railstutorial.org/ruby-on-rails-tutorial-book">The Ruby on Rails Tutorial</a></h4>
      <p>One of the best Ruby on Rails tutorials around, from zero to deploy.</p>
    </li>

    <li>
      <h4><a href="http://www.khanacademy.org/">Khan Academy</a></h4>
      <p>Hours of video on data types to Fibonacci functions and everything in-between.</p>
    </li>

    <li>
      <h4><a href="http://help.github.com/">Github Guide to Git</a></h4>
      <p>Github's guide to using the git version control system.</p>
    </li>

    <li>
      <h4><a href="http://dribbble.com/">Dribbble</a></h4>
      <p>The best place to go for design inspiration.</p>
    </li>

    <li>
      <h4><a href="http://news.ycombinator.com/">Hacker News</a></h4>
      <p>The Hacker Hub. Everything from news, to tutorials, to startups. Bookmark this.</p>
    </li>

	<li>
      <h4><a href="http://scratch.mit.edu/">Scratch</a></h4>
      <p>Scratch is a programming language that makes it easy to create your own interactive stories, animations, games, music, and art.</p>
    </li>

	<li>
      <h4><a href="http://en.wikipedia.org/wiki/Logo_%28programming_language%29">Logo</a></h4>
      <p>Logo is a multi-paradigm computer programming language first made for <a href="http://www.nasa.gov/">NASA</a> a long time ago, and used in education.</p>
    </li>

	<li>
      <h4><a href="http://www.alice.org/index.php">Alice</a></h4>
      <p>Alice is a 3d programming environment, designed to &ldquo;create an animation for telling a story&rdquo;.</p>
    </li>

    <li>
      <h4><a href="http://www.alice.org/kelleher/storytelling/download.html">Story Telling Alice</a></h4>
      <p>Designed to motivate a broad spectrum of middle school students (particularly girls) to learn to program computers through creating short 3D animated movies. <strong>Note:</strong> Story Telling Alice is not hugely tested, is only available for windows based machines, and has no support.</p>
    </li>

	<li>
      <h4><a href="http://en.wikipedia.org/wiki/Android_%28operating_system%29">Android</a></h4>
      <p>Android is a mobile operating system for mobile devices such as mobile telephones and tablet computers developed by the Open Handset Alliance.</p>
    </li>

	<li>
      <h4><a href="http://en.wikipedia.org/wiki/Lego_Mindstorms">Lego Mindstorm</a></h4>
      <p>Programmable lego.</p>
    </li>

	<li>
      <h4><a href="http://learnpythonthehardway.org/">Learn Python The Hard Way</a></h4>
      <p>Emphasizes precision, attention to detail, and persistence.</p>
    </li>

	<li>
      <h4><a href="http://www.codeproject.com/KB/android/AndroidGuide.aspx">Code Project</a></h4>
      <p>A great page on Android programming (for mobiles) there are many tutorials for Android.</p>
    </li>

	<li>
      <h4><a href="http://www.blitzgamesstudios.com/blitz_academy/resources/">Blitz Academy</a></h4>
      <p>A list of resources for those thinking about getting a job as a games developer.</p>
    </li>

	<li>
      <h4><a href="http://www.gamebooks.org/show_series.php?id=1171">Bytes Brothers</a></h4>
      <p>A cross between Encyclopedia Brown and Micro Adventure, each volume in this series contains several short mysteries. The user must read carefully and run very simple BASIC computer programs in order to guess the solutions.</p>
    </li>
</ul>