<style>

ul.resources {
	margin:0px;
	padding:0px;
}

ul.resources li {
	padding:10px;
	border:#999 1px solid;
	margin:0px 20px 20px 0px;
	list-style:none;
	width:190px;
	float:left;
	height:140px;
	overflow:hidden;
}

h3 {clear:both;margin:10px;}

</style>

<h3>Resources Page</h3>
For our awesome resources page of all things YRS 2012, please click <a href="http://share.jellybabi.es/yrs">here</a>.
