<div class="row">
	<div class="span8">
		<p>We know you guys like bullet points, so here they are:</p>

<p>SAP YRS 2012 happens in centres across the UK — a centre is a business that has space and wifi to take up to 10 kids</p>

<ul><li>we assign kids from central sign up as well as local recruiting (by centres)</li>
<li>we ensure that each centre has at least one mentor for the Monday - Thursday</li>
<li>we are trying to assign one alumnus per centre this year as well (but that might not be possible)</li></ul>

<h2>Mentors will:</h2>
<ul><li>help the kids get ideas in the first place (Monday)</li>
<li>understand the data</li>
<li>help with programming where necessary</li>
<li>do stand up presentations with the kids every day</li>
<li>liaise with each other and share skills remotely if necessary</li>
<li>assist with the prep for final presentation</li>
<li>be invited to mentor at the festival of code on the Friday/Saturday when all the kids are together</li></ul>

		
	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Signups for SAP YRS 2012 are now closed. Express interest in the even-bigger YRS 2013!</p>
			<p><a href="./signup.html" class="btn btn">Sign up now! &rarr;</a></p>
		</div>
		<img src="http://farm7.staticflickr.com/6009/6012388041_39aa2c3686_b.jpg" />
	</div>
</div>