<div class="row">
	<div class="span8">
		<p>We know you guys like bullet points, so here they are:</p>

<p>YRS happens in centres across the UK — a centre is a business that has space and wifi to take up to 10 kids</p>

<ul><li>we assign kids from central sign up as well as local recruiting (by centres)</li>
<li>we ensure that each centre has at least one mentor for the Monday - Thursday</li>
<li>we are trying to assign one alumnus per centre this year as well (but that might not be possible)</li></ul>

<h2>Mentors will:</h2>
<ul><li>help the kids get ideas in the first place (Monday)</li>
<li>understand the data</li>
<li>help with programming where necessary</li>
<li>do stand up presentations with the kids every day</li>
<li>liaise with each other and share skills remotely if necessary</li>
<li>assist with the prep for final presentation</li>
<li>be invited to mentor at the festival of code on the Friday/Saturday when all the kids are together</li></ul>

<h2><abbr>F.A.Q.</abbr></h2>

<p><strong>Q:</strong> Will mentors get Tee Shirts?<br/>
<strong>A:</strong> Yes.</p>
<p><strong>Q:</strong> Will travel and subsistence be covered for mentors?<br/>
<strong>A:</strong> Assuming we get the sponsorship we are aiming for then yes. If not, there will be a hardship pot.</p>
<p><strong>Q:</strong> Do mentors need to be available every day of the week 6 &rarr; 12th August?<br/>
<strong>A:</strong> Not at all, we will be in touch and will work out which days you are free. But be warned, it is very addictive and compelling and you will want to be there, especially at the end!</p>
<p><strong>Q:</strong> Can I chat to a mentor who has done it before?<br/>
<strong>A:</strong> Yes, we plan to ask a few mentors from previous years to be available for queries. In the first instance please contact David Durant.</p>
<p><strong>Q:</strong> Do I need to be CRB checked?<br/>
<strong>A:</strong> No but there will be no 1-2-1 mentoring, everything will happen in a single open space (this will be the centres to sort). We are looking into the rules for the festival at the end of the week. So watch this space.</p>
		
	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Hurry! There's not long left to sign up for YRS 2012! You'll hear back from us in a couple of days when we've found you a centre. Go!</p>
			<p><a href="#" class="btn btn-primary">Sign up now! &rarr;</a></p>
		</div>
		<img src="http://farm7.staticflickr.com/6009/6012388041_39aa2c3686_b.jpg" />
	</div>
</div>