<div class="row">
	<div class="span12">
		<iframe src="https://cms.youngrewiredstate.org/data/api/centres.example" style="width: 100%; height: 620px; border: none;"></iframe>
		
	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Signups for 2012 are now closed. Express interest in the even-bigger YRS 2013!</p>
			<p><a href="./signup.html" class="btn btn">Sign up now! &rarr;</a></p>
		</div>
	</div>
	<div class="span8">
		<h2>YRS: Festival of Code 2012</h2>
		<p>The event is spread across the entire of the UK. If there's not a centre near you, have you considered hosting one?</p>
	</div>
</div>