<div class="row">
            <div class="span8">
            <p>Young Rewired State is free for your child. It runs from the 6 → 12<sup>th</sup> August and we will aim to find a local centre for your child. If no local centre can be found, we will offer to mentor them remotely and they will be invited to come to the festival of code, and to the show and tell on the Saturday.
            We will be in touch with your child directly to send them information about the event, the centre that they have been allocated to and some resources for them to brush up their skills or acquire some basics.
            Each centre will be different, some will provide lunches and some will not — you will get detailed information about these practical things from the centre itself in June.
            You will be expected to cover the costs for getting your child to and from the centre each day.</p>
            <h2>The Friday and Saturday festival</h2>
            <p>This year all of the young people who take part in YRS are invited to spend the Friday (and Saturday) night at the festival of code at the Custard Factory in Birmingham. They will have a massive sleepover with coding, practising their presentations and so on — as well as all meeting each other and having a brilliant time. Each centre will organise the travel to Birmingham and will go with the young people, continuing to work with them during the time they are there. If your child is being mentored remotely, the mentor will organise this with you.</p>
			<p>There will be a huge show and tell on the Saturday to a selection of press, government, industry, sponsors and people who want to support them — you are all welcome. There is no pre-requisite for the Saturday show and tell kids to have been at the camp over the night before, they can just come on the Saturday morning for the presentations.</p>
            <p><span class="label label-info">Important:</span> <strong>We will need to be alerted to any medical needs/allergies. Centres will collect this information in July.</strong></p>
                        <h2>Further information</h2>

            <p>This year we have asked for a number of parents from previous years to act as points of contact for all of you — for any questions you may want to ask a parent who has had a child attend Young Rewired State before.</p>
            <p>The contact details for these parents will be shared with you through your child (once they have registered) but in the first instance, please <a href="mailto:angijlong@gmail.com"> contact "Angi L"</a>.
              To speak to one of the organisers about other practical matters, please use the <a href="/contact/">contact details</a> on this site.
            </p>
            </div>
            <div class="span4"><h2>Checklist</h2>
            <h3>For the week</h3>
            <ul>
                <li><p>Transport to and from the centre each day</p></li>
                <li><p>Possibly packed lunch or money for lunch</p></li>
                <li><p>A laptop</p></li>
            </ul>
            <h3>For the Festival of Code</h3>
            <ul>
                <li><p>Funds to get to the site</p></li>
                <li><p>Sleeping bag</p></li>
                <li><p>Toiletries</p></li>
                <li><p>Your contact details</p></li>
            </ul>
			<h2>Rules</h2>
            <h3>Festival of Code Sleepover Rules</h3>
            <p><strong>Please check back regularly, as these rules are subject to change before the event!</strong></p>
            <ul>
                <li><p>Age limit: 18 years and under (no lower age range)</p></li>
                <li><p>Young people aged 18+ will sleep in a separate area</p></li>
                <li><p>Young people aged 14-17 will sleep in a separate area, with written parental/guardian agreement provided to Rewired State</p></li>
                <li><p>Young people aged 13 and under will need to be accompanied by a parent or carer and will be in a further segregated area</p></li>
            </ul>
            </div></div>