<div class="row">
	<div class="span6 offset3">
		<p>Earlier this year, Young Rewired State successfully raised £20,000 in private, crowd-sourced donations through a <a href="http://www.peoplefund.it/young-rewired-state/">PeopleFund.it</a> campaign.</p>
		<p>We're enormously thankful to the following organizations and people who have funded YRS 2012 so far. If you would like to make a personal donation, please contact Emma.</p>
		<p>Thank you.</p>
		<p>&nbsp;</p>
		</div>
	<div class="span12" style="" id="sponsorspage">
		<div class="row">
		<div class="span4 offset4">
		<div class="well">
			<h3>Deputy Head: The Indigo Trust</h3>
			<img src="http://youngrewiredstate.org/img/sponsors/indigotrust.jpg" />
		</div>
		</div></div>
		<div class="">
		<h3>Joint Heads of P.E.</h3>
		<div class="row">
		<ul>
		<li><img alt="Go Squared" src="http://youngrewiredstate.org/img/sponsors/gosquared.png" /></li>
		<li><img alt="Made By Many" src="http://youngrewiredstate.org/img/sponsors/madebymany.png" /></li>
		<li><img alt="Realtime Club" src="http://youngrewiredstate.org/img/sponsors/realtimeclub.png" /></li>
		<li><img alt="SendGrid" src="http://youngrewiredstate.org/img/sponsors/sendgrid.png" /></li>
		<li><img alt="Shuttleworth Foundation" src="http://youngrewiredstate.org/img/sponsors/shuttleworth-foundation.png" /></li>
		<li><img alt="Sleepy Dog" src="http://youngrewiredstate.org/img/sponsors/sleepydog.png" /></li>
		<li><img alt="Three" src="http://youngrewiredstate.org/img/sponsors/three.png" /></li>
		</ul>
		</div>
		</div>
		
		<div class="well" style="clear:both;margin-top:70px;height:100px">
        <h3>Senior Prefects</h3>
		<ul>
        <li>
            <p><a href="http://google.co.uk/"><img alt="Google UK" src="http://youngrewiredstate.org//img/sponsors/google.png"></a></p>
        </li><!-- closing grid3 -->

        <li>
            <p><a href="http://oreilly.com/"><img alt="O' Reilly" src="http://youngrewiredstate.org//img/sponsors/oreilly.png"></a></p>
        </li><!-- closing grid3 -->

        <li>
            <p><a href="http://developer.pearson.com"><img alt="Pearson" src="http://youngrewiredstate.org//img/sponsors/pearson.png"></a></p>
        </li><!-- closing grid3 -->
		</ul>
		</div>
		
		<div style="clear:both">
        <h3>Line Leaders</h3>
            <p>If you'd like to be a line-leader, please apply to the School <a href="mailto:hello@youngrewiredstate.org">Secretary</a>.</p>
		<ul>
			<li>
				<a href="http://agant.com/"><img alt="Agant" src="http://youngrewiredstate.org/img/sponsors/agant.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.bcs.org/"><img alt="British Computing Society" src="http://youngrewiredstate.org/img/sponsors/bcs.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://scraperwiki.com"><img alt="ScraperWiki" src="http://youngrewiredstate.org/img/sponsors/scraperwiki.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.literatureandlatte.com/scrivener.php"><img alt="YouSrc" src="http://youngrewiredstate.org/img/sponsors/scrivener.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.trafficdigital.com/"><img alt="Traffic" src="http://youngrewiredstate.org/img/sponsors/traffic.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.yousrc.com/"><img alt="YouSrc" src="http://youngrewiredstate.org/img/sponsors/yousrc.png"></a>
			</li>
			
			<li>
				<a href="http://www.tso.co.uk"><img alt="The Stationery Office" src="http://youngrewiredstate.org/img/sponsors/TSO.jpg" /></a>
			</li>
			<!-- closing grid3 -->

            <br>

    </div>
		
    </div>
	</div>
</div>