<div class="row">
	<div class="span8">
		<div class="row">
			<div class="span8">
				<p style="padding-bottom:20px;">We have a large team working behind the scenes. The best people to contact with your questions are Lawrence and Kevin (kids questions) or Angi (a parent of a YRS alumnus). Telephone numbers, Twitter handles and addresses for more general enquiries can be found on the main contact page. <a href="/contact/">Go to the main contact page &raquo;</a></p>
			</div>
			<div class="span4">
				<div class="well">
					<h3>Angi L</h3>
					<p>Angi L is available for any questions about the event from a parent's perspective.</p>
					<a class="btn btn-primary">Email Angi L</a>
				</div>
			</div>
			<div class="span4">
				<div class="well">
					<h3>Emma & Neil</h3>
					<p>Emma and Neil are available for any questions about the event from kids and parents.</p>
					<a class="btn">Email Emma &amp; Neil.</a>
				</div>
			</div>
		</div>
	</div>
	<div class="span4">
		<img class="fluid" src="http://farm7.staticflickr.com/6122/6012046689_2e5e500d2a_b.jpg" />
	</div>
</div>
