<div class="row">
            <div class="span8">
                <img src="http://farm7.staticflickr.com/6011/6012034077_a2257559d5_b.jpg" class="fluid" />
                <div class="section" style="padding-top:20px;">
                    <h2>Young Rewired State</h2>
                    <p>Young Rewired State is free for your child. It runs from the 6 &rarr; 12th August and we will aim to find a local centre for your child. If no local centre can be found, we will offer to mentor them remotely and they will be invited to come to the festival of code, and to the show and tell on the Saturday. We will be in touch with your child directly to send them information about the event, the centre that they have been allocated to and some resources for them to brush up their skills or acquire some basics. Each centre will be different, some will provide lunches and some will not — you will get detailed information about these practical things from the centre itself in July. You will be expected to cover the costs for getting your child to and from the centre each day.</p>
                    <p>This website has been designed to be as useful as possible for parents. However, if there is something we haven't explained, feel free to contact us at any time.</p>
                </div>
            </div>
            <div class="span4"><h2>Checklist</h2>
            <h3>For the week</h3>
            <ul>
                <li><p>Transport to and from the centre each day</p></li>
                <li><p>Possibly packed lunch or money for lunch</p></li>
                <li><p>A laptop</p></li>
            </ul>
            <h3>For the Festival of Code</h3>
            <ul>
                <li><p>Funds to get to the site</p></li>
                <li><p>Sleeping bag</p></li>
                <li><p>Toiletries</p></li>
                <li><p>Your contact details</p></li>
            </ul>
			<h2>Rules</h2>
            <h3>Festival of Code Sleepover Rules</h3>
            <p><strong>Please check back regularly, as these rules are subject to change before the event!</strong></p>
            <ul>
                <li><p>Age limit: 18 years and under (no lower age range)</p></li>
                <li><p>Young people aged 18+ will sleep in a separate area</p></li>
                <li><p>Young people aged 14-18 will sleep in a separate area, with written parental/guardian agreement provided to Rewired State</p></li>
                <li><p>Young people aged 13 and under will need to be accompanied by a parent or carer and will be in a further segregated area (these may stay on Friday night only)</p></li>
            </ul>
            </div></div>