<div class="row">
	<div class="span8">
		<div id="kids-carousel" class="carousel slide">
			<!-- Carousel items -->
			<div class="carousel-inner" style="height:500px;">
				<div class="item active"><iframe width="100%" height="480" src="http://www.youtube.com/embed/odT4cgd7d8c?rel=0&theme=light&controls=0&color=white" frameborder="0" allowfullscreen></iframe></div>
				<div class="item"><img src="http://farm7.staticflickr.com/6124/6012035074_a3344529e7_b.jpg" class="fluid" /></div>
				<div class="item"><img src="http://farm7.staticflickr.com/6122/6012361279_c47cbb32e4_b.jpg" class="fluid" /></div>
				<div class="item"><img src="http://farm7.staticflickr.com/6141/6012205431_a03d083279_b.jpg" class="fluid" /></div>
				<div class="item"><img src="http://farm7.staticflickr.com/6017/6012570604_d942b4c48e_b.jpg" class="fluid" /></div>
				<div class="item"><img src="http://farm7.staticflickr.com/6129/6012533302_fb5d8b2db7_b.jpg" class="fluid" /></div>
				<div class="item"><img src="http://farm7.staticflickr.com/6011/6012034077_a2257559d5_b.jpg" class="fluid" /></div>
			</div>
			<!-- Carousel nav -->
			<a class="carousel-control left" href="#kids-carousel" data-slide="prev">&lsaquo;</a>
			<a class="carousel-control right" href="#kids-carousel" data-slide="next">&rsaquo;</a>
		</div>
		
	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Hurry! There's not long left to sign up for YRS 2012! You'll hear back from us in a couple of days when we've found you a centre. Go!</p>
			<p><a href="#" class="btn btn-primary">Sign up now! &rarr;</a></p>
		</div>
		<h2>YRS: Festival of Code 2012</h2>
		<p>The YRS festival of code is the fourth annual competition hosted by <a href="http://rewiredstate.org">Rewired State</a>. The event takes place simultaneously across the UK 
		for the week learind up to the giant festival of code.</p>
		<ul>
			<li>Compete for awesome prizes</li>
			<li>Make a difference to the world with your idea</li>
			<li>Learn some awesome new skills</li>
			<li>Meet other people as fascinating as you!</li>
			<li>Did I mention the prizes?</li>
		</ul>
		<p>What are you waiting for? Get signed up now or explore the site for more info!</p>
		<p>Lawrence</p>
	</div>
</div>