<div class="row">
	<div class="span8">
		<p>YRS centres are organisations across the UK who have space to host at least three young people. Ideally you would have some developers in-house, but we will send mentors and/or alumni for the week. </p>
<p>You will need to have wifi (very important) and have one person from your organisation as the main point of contact and available that week 6 → 12th August. </p>
<p>We are signing young people up centrally who hear about this through the media but we also would expect you to recruit locally. (We support you in these efforts, but it is of great benefit to you to build those relationships with your local coding youth!). </p>
<p>We assign young people to centres from Easter holidays through to August, and where we have centres and no young people we make every effort to help you recruit locally and where we have young people and no centres, we seek out centres — it is quite simple really!</p>

	</div>
	<div class="span4">
		<div class="well">
			<h2>Sign Up</h2>
			<p>Hurry! There's not long left to sign up for YRS 2012! You'll hear back from us in a couple of days.</p>
			<p><a href="#" class="btn btn-primary">Sign up now! &rarr;</a></p>
		</div>
		<img src="http://farm7.staticflickr.com/6009/6012388041_39aa2c3686_b.jpg" />
	</div>
</div>