<div class="row">
	<div class="span6 offset3">
		<p>Earlier this year, Young Rewired State successfully raised £20,000 in private, crowd-sourced donations through a <a href="http://www.peoplefund.it/young-rewired-state/">PeopleFund.it</a> campaign.</p>
		<p>We're enormously thankful to the following organizations and people who have funded YRS 2012 so far. If you would like to make a personal donation, please contact Emma.</p>
		<p>We are now welcoming sponsors for Young Rewired State 2013 - an event even bigger and better than this year! Please <a href="mailto:emma@rewiredstate.org">contact Emma</a> for more information.</p>
		<p>Thank you.</p>
		<p>&nbsp;</p>
		</div>
	<div class="span12" style="" id="sponsorspage">
	<h2>Headline Sponsor: SAP</h2>
	<ul class="sponsors headlineSAP">
		<li><a href="http://www.sap.com/uk/index.epx"><img alt="SAP" src="/assets/sap-large.png" /></a></li>
	</ul>
	
	
			<h2>Deputy Heads: The Indigo Trust & Three</h2>
			<ul class="deputyheads">
			<li><img src="/assets/sponsors/indigo.jpg" /></li>
			<li><img alt="Three" src="/assets/sponsors/three.jpg" /></li>
			</ul>
		<div class="">
		<h2>Joint Heads of P.E.</h2>
		<ul class="sponsors jhoPE">
		<li><img alt="Go Squared" src="http://youngrewiredstate.org/img/sponsors/gosquared.png" /></li>
		<li><img alt="Made By Many" src="http://youngrewiredstate.org/img/sponsors/madebymany.png" /></li>
		<li><img alt="Realtime Club" src="http://youngrewiredstate.org/img/sponsors/realtimeclub.png" /></li>
		<li><img alt="SendGrid" src="http://youngrewiredstate.org/img/sponsors/sendgrid.png" /></li>
		<li><img alt="Shuttleworth Foundation" src="http://youngrewiredstate.org/img/sponsors/shuttleworth-foundation.png" /></li>
		<li><img alt="Sleepy Dog" src="http://youngrewiredstate.org/img/sponsors/sleepydog.png" /></li>
		<li><img alt="CloudFoundry" src="http://youngrewiredstate.org/img/sponsors/cloudfoundry.jpg" /></li>
		<li><img alt="Twilio" src="http://youngrewiredstate.org/img/sponsors/twilio_downloadable_logobrand.png" /></li>
		</ul>
		</div>
		
        <h2>Senior Prefects</h2>
		<ul class="sponsors seniorprefects">
        <li>
            <p><a href="http://google.co.uk/"><img alt="Google UK" src="/assets/sponsors/google.png"></a></p>
        </li><!-- closing grid3 -->

        <li>
            <p><a href="http://oreilly.com/"><img alt="O' Reilly" src="/assets/sponsors/oreilly.png"></a></p>
        </li><!-- closing grid3 -->

        <li>
            <p><a href="http://developer.pearson.com"><img alt="Pearson" src="/assets/sponsors/pearson.png"></a></p>
        </li><!-- closing grid3 -->

        <li>
            <p><a href="http://web.aqa.org.uk/qual/newgcses/ict/computer-science-overview.php?id=10&__utma=43460533.1102982496.1333622839.1333622839.1334133713.2&__utmb=43460533.4.10.1340882663&__utmc=43460533&__utmx=-&__utmz=43460533.1333622839.1.1.utmcsr=intranet|utmccn=(referral)|utmcmd=referral|utmcct=/&__utmv=-&__utmk=58535023"><img alt="AQA" src="/assets/sponsors/aqa-logo-200x100.gif"></a></p>
        </li><!-- closing grid3 -->

        <li>
            <p><a href="http://dxw.com/"><img alt="DXW" src="/assets/sponsors/dxw.png"></a></p>
        </li><!-- closing grid3 -->
		</ul>
		
		<div style="clear:both">
        <h2>Line Leaders</h2>
            <p>If you'd like to be a line-leader, please apply to the School <a href="mailto:hello@youngrewiredstate.org">Secretary</a>.</p>
		<ul class="sponsors lineleaders">
			<li>
				<a href="http://agant.com/"><img alt="Agant" src="http://youngrewiredstate.org/img/sponsors/agant.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.bcs.org/"><img alt="British Computing Society" src="http://youngrewiredstate.org/img/sponsors/bcs.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://scraperwiki.com"><img alt="ScraperWiki" src="http://youngrewiredstate.org/img/sponsors/scraperwiki.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.literatureandlatte.com/scrivener.php"><img alt="YouSrc" src="http://youngrewiredstate.org/img/sponsors/scrivener.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.trafficdigital.com/"><img alt="Traffic" src="http://youngrewiredstate.org/img/sponsors/traffic.png"></a>
			</li><!-- closing grid3 -->
			
			<li>
				<a href="http://www.yousrc.com/"><img alt="YouSrc" src="http://youngrewiredstate.org/img/sponsors/yousrc.png"></a>
			</li><!-- closing grid3 -->

            <br>

    </div>
	<div>
		<h2>Official Media Partner: The Kernel.<h2>
		
	</div>
		
    </div>
	</div>
</div>