<div class="row">
    <div class="span6 offset3">
	<p>Earlier this year, Young Rewired State successfully raised &pound;20'000 in private, crowd-sourced donations through a <a href="http://www.peoplefund.it/young-rewired-state/">PeopleFund.it</a> campaign.</p>

        <p>In the campaign, we said that we'd say thank you on the website to those who dipped into their pockets. Here it is (in alphabetical order). We couldn't have done it without you. Thank you very much.</p>

        <p>If you'd rather not appear on this list, please do <a href="mailto:webmaster@youngrewiredstate.org">get in touch</a> and one of the gang will remove you from the list.</p>
    </div>

    <div class="span12" style="" id="sponsorspage">
        <div>
            <h2>&pound;10 or more</h2>
            <ul class="sponsors pfi-10">
                <p><li><a href="http://www.peoplefund.it/user/adamcohenrose/">adamcohenrose</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/alobear1/">alobear1</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/andyxmas/">andyxmas</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/benosteen/">benosteen</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/boleyn/">boleyn</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/campbell.chris2/">campbell.chris2</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/chas.linn/">chas.linn</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/cholten99/">cholten99</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/citizensheep/">citizensheep</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/clarehat/">clarehat</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/clive-wales/">clive-wales</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/coldclimate/">coldclimate</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/connorroberts/">connorroberts</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/danlockton/">danlockton</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/davenportmb/">davenportmb</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/don.connolly/">don.connolly</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/duncan.geere/">duncan.geere</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/edent/">edent</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/felixgreaves/">felixgreaves</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/genevievet/">genevievet</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/georgiawarren/">georgiawarren</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/grahamk/">grahamk</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/hjwp/">hjwp</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/hughknowles/">hughknowles</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/issyl0/">issyl0</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/james.gurling/">james.gurling</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/james.smith/">james.smith</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jane.lomax/">jane.lomax</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jleawilson/">jleawilson</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/JMFoxy/">JMFoxy</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jo.broom/">jo.broom</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jonfoster/">jonfoster</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/josh.weinberg/">josh.weinberg</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jot/">jot</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/katebennet/">katebennet</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/katenorman/">katenorman</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/kevinbeynon/">kevinbeynon</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mike.saunby/">mike.saunby</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mike.wooldridge/">mike.wooldridge</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mikey3982/">mikey3982</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/nhawthorn/">nhawthorn</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/owen.stephens/">owen.stephens</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/paul_clarke/">paul_clarke</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/paulstamp/">paulstamp</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/petelanc/">petelanc</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/philip.colligan/">philip.colligan</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/phill-ash/">phill-ash</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/puntofisso/">puntofisso</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/richard.mallender/">richard.mallender</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/richard30/">richard30</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/seo01/">seo01</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/simondev/">simondev</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/simonwheatley/">simonwheatley</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/tomblomfield/">tomblomfield</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/tomblomtest/">tomblomtest</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/vickytnz/">vickytnz</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/helenmilner/">helenmilner</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/claredavenport/">claredavenport</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/dankarran/">dankarran</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/feargalhogan/">feargalhogan</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/gavinatkinson/">gavinatkinson</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/icerunner/">icerunner</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/kengo/">kengo</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/kzherebtsova/">kzherebtsova</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/leisareichelt/">leisareichelt</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mattlucht/">mattlucht</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mdb36/">mdb36</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mrbootle/">mrbootle</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/MsSaraKelly/">MsSaraKelly</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/paul_clarke/">paul_clarke</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/saulcozens/">saulcozens</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/tmhrtly/">tmhrtly</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/carrinagaffney/">carrinagaffney</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/icerunner/">icerunner</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/nigelm/">nigelm</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/sitar/">sitar</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jon.sowler/">jon.sowler</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mikelittle/">mikelittle</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/kavitakapoor/">kavitakapoor</a></li></p>
            </ul>
        </div>

        <div>
            <h2><h2>&pound;50 or more</h2>
            <ul class="sponsors pfi-50">
                <p><li><a href="http://www.peoplefund.it/user/amcunningham/">amcunningham</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/anniebonne/">anniebonne</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/baskers/">baskers</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/bevangelist/">bevangelist</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/colin-hayhurst/">colin-hayhurst</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/davorg/">davorg</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/dhs/">dhs</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/iamleeg/">iamleeg</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/ilk21/">ilk21</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jdfairbairn/">jdfairbairn</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jon.kingsbury/">jon.kingsbury</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/lou31/">lou31</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mark.chapman/">mark.chapman</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mark.oneill/">mark.oneill</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/martine.garland/">martine.garland</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/mrchrisadams/">mrchrisadams</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/nick.harewood/">nick.harewood</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/psd/">psd</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/purplesime/">purplesime</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/qmacro/">qmacro</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/rejoco/">rejoco</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/robb1e/">robb1e</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/rorycellan/">rorycellan</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/sara.nicholls1/">sara.nicholls1</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/sblomley/">sblomley</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/scz/">scz</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/stevieflow/">stevieflow</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/tim.morley/">tim.morley</a></li></p>
            </ul>
        </div>

        <div>
            <h2>&pound;100 or more</h2>
            <ul class="sponsors pfi-100">
                <p><li><a href="http://www.peoplefund.it/user/1jh/">1jh</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/46bit/">46bit</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/amanda.dowling/">amanda.dowling</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/brian.pixelpin.taylor/">brian.pixelpin.taylor</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/bugshaw/">bugshaw</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/cholten99/">cholten99</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/eduserv/">eduserv</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/grahambrownmartin/">grahambrownmartin</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/helpfultechnology/">helpfultechnology</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/jaggeree/">jaggeree</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/john_w_lazar/">john_w_lazar</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/juliac/">juliac</a></li></p>
            </ul>
        </div>

        <div>
            <h2>&pound;200 or more</h2>
            <ul class="sponsors pfi-200">
                <p><li><a href="http://www.peoplefund.it/user/kspelk2/">kspelk2</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/nick_appleyard/">nick_appleyard</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/simon.peyton.jones/">simon.peyton.jones</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/sjlovell/">sjlovell</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/Stefl/">Stefl</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/timdavies/">timdavies</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/ve-interactive/">ve-interactive</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/justincooke/">justincooke</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/kspelk2/">kspelk2</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/meriwilliams/">meriwilliams</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/willguv/">willguv</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/harrym/">harrym</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/bluedaniel/">bluedaniel</a></li></p>
            </ul>
        </div>

        <div>
            <h2>&pound;500 or more</h2>
            <ul class="sponsors pfi-500">
                <p><li><a href="http://www.peoplefund.it/user/alan-smith/">alan-smith</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/bjpirt/">bjpirt</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/marwood/">marwood</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/nomad-coop/">nomad-coop</a></li></p>
            </ul>
        </div>

        <div>
            <h2>&pound;1000 or more</h2>
            <ul class="sponsors pfi-1k">
                <p><li><a href="http://www.peoplefund.it/user/julia/">julia</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/paulbirch99/">paulbirch99</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/pvm/">pvm</a></li></p>
                <p><li><a href="http://www.peoplefund.it/user/timdawson/">timdawson</a></li></p>
            </ul>
        </div>

    </div><!-- close div class="span12" style="" id="sponsorspage" -->
</div> <!-- close div class="row" -->
