<div class="row">
	<div class="span6 offset3" style="padding:50px 0 200px 0;">
		<p>We're enormously thankful to the organizations and people who have funded YRS 2012 so far. If you would like to make a personal donation, please contact Emma.</p>
		<p>We still have openings for more organisations to sponsor us. We, and the 500 participants this year would be incredibly grateful if you could consider a sponsorship.
		Please contact Emma if you would like to know what we can offer in return.</p>
		<p>Thank you.</p>
	</div>
</div>