<div class="row">
	<div class="span6 offset3" style="padding:50px 0 200px 0;">
		<p>We're enormously thankful to the organizations and people who have funded YRS 2012 so far.</p>
		<p>We are now welcoming sponsors for Young Rewired State 2013 - an event even bigger and better than this year! Please <a href="mailto:emma@rewiredstate.org">contact Emma</a> for more information.</p>
		<p>Thank you.</p>
	</div>
</div>